[pytest]
DJANGO_SETTINGS_MODULE = yanews.settings
django_find_project = false
pythonpath = .
testpaths = news/pytest_tests
norecursedirs = .* venv ya-note
confcutdir = .
addopts = --strict-markers -v --create-db
