[pytest]
# Настройки Django
DJANGO_SETTINGS_MODULE = yanote.settings
django_find_project = false
pythonpath = .

# Папки с тестами (строго одна строка testpaths!)
testpaths = notes/pytest_tests

# Опции по умолчанию
addopts = 
    --strict-markers
    -vv
    --color=yes

# Регистрация кастомных маркеров
markers =
    slow: Медленные тесты
    db: Тесты с БД
    api: Тесты внешних запросов

# Скрыть предупреждения (опционально)
filterwarnings =
    ignore::DeprecationWarning
